# Generated by Django 3.0 on 2020-05-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200510_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='shop/images')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('desc', models.CharField(max_length=3000)),
            ],
        ),
    ]
